# Generated by Django 5.1.5 on 2025-11-11 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_day_scholar', models.BooleanField(default=True)),
                ('amt_paid', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=32)),
                ('entry_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('exit_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.messprofile')),
            ],
            options={
                'unique_together': {('user', 'session_id')},
            },
        ),
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=512, unique=True)),
                ('device_id', models.CharField(max_length=128)),
                ('gate_id', models.CharField(max_length=32)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.messprofile')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.messvisit')),
            ],
        ),
    ]
